framework:
  messenger:
    default_bus: default.bus
    buses:
      default.bus:
      command.bus:
        default_middleware:
          enabled: true
          allow_no_handlers: false
      query.bus:
        default_middleware:
          enabled: true
          allow_no_handlers: false
      domain.event.bus:
        default_middleware:
          enabled: true
          allow_no_handlers: true
      integration.event.bus:
        default_middleware:
          enabled: true
          allow_no_handlers: false
        middleware:
          - App\Common\Infrastructure\Bus\Middleware\IntegrationLoggingMiddleware
    failure_transport: failed

    transports:
      # https://symfony.com/doc/current/messenger.html#transport-configuration
      async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
          use_notify: true
          check_delayed_interval: 60000
        retry_strategy:
          max_retries: 3
          multiplier: 2
      failed: 'doctrine://common?queue_name=failed'
      # sync: 'sync://'

    routing:
      Symfony\Component\Mailer\Messenger\SendEmailMessage: async
      Symfony\Component\Notifier\Message\ChatMessage: async
      Symfony\Component\Notifier\Message\SmsMessage: async

      # Route your messages to the transports
      'App\Common\Integration\*': async
      'App\Search\Integration\*': async
      'App\Loan\Integration\*': async
